### PR TITLE
Fixed machineNetwork typo

### PR DESCRIPTION
**Pull request by benswinney**
machineNetwork in install-config-upi.yaml should be machineNetworkCIDR

### CODE REVIEW

**Comment by cgruver** [comment]
@benswinney  Thanks for the update.

What's interesting, is that the install has been working with the entry as it currently is.  Is it possible that this is not really used by the installer?  This install-config.yaml was actually modified from one originally built to do a bare-metal IPI install.

**Comment by cgruver** [comment]
I double checked the entry against the docs at:

https://github.com/openshift/installer/blob/master/docs/user/customization.md

It looks like it is correct as written.  Are you seeing an issue creating the ignition configs?

However, the docs at: https://github.com/openshift/installer/blob/master-fcos/docs/user/customization.md, use `machineCIDR` instead of `machineNetwork`...  So, now I am confused...  ;-)

**Comment by benswinney** [comment]
When I ran the openshift-install to create the manifests, I got the following error:

$ openshift-install create manifests --dir=okd4/
FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to unmarshal install-config.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Networking.networking.machineNetwork of type types.MachineNetworkEntry

When I updated the install-config.yaml file to be machineNetworkCIDR, then no errors were produced.

Looking at the link you've provided, it actually should be:


machineNetwork:
  \- cidr: 10.0.0.0/16

I've retested it as using the above config and it works. So you can probably close this commit and reject. I can raise a new one with the correct config.

**Comment by cgruver** [comment]
Try it without that entry at all.  It will probably work.  I suspect that the entry isn't actually necessary for UPI.  In my case the network literally is 10.11.11.0/24.  That may be why I don't see errors when creating the ignition configs.  

I think that the installer we are using is build from the `fcos` branch now, but I'm not positive.

https://github.com/openshift/installer/blob/fcos/docs/user/customization.md

**Comment by cgruver** [comment]
I removed the machineNetwork entry.  I'm pretty sure it is unnecessary for UPI installation.

**Comment by benswinney** [comment]
Cool. I'll close this pull request.

**Pull request closed without merging**
